harvardinformatics/snpArcher

- Snakefile_fastq2bam
- Snakefile_intervals
- config.yaml
- envs/fastq2bam.yml
- resources.yaml
- rules/fastq2bam.smk
- added resource requests for new SRA/download rules
- switched genome download to a local rule
- changed genome download to unzip with PKZIP instead of unzip (NCBI datasets decompression was throwing a ```need PK compat. v4.5 (can do v2.1)``` error)
- added p7zip as dependency for fastq2bam workflow
- added command to combine genome download files into one genome FASTA because NCBI datasets download splits reference genomes into chromosome/scaffold-specific FASTAs
- added variable to config for samples metadata sheet to avoid hardcoding file name in snakefile
- added resource requests for intervals workflow
- removed redundant lines from testing that were commented out
> Resource update

- envs/bam2vcf.yml
- helperFun.py
- resources.yaml
- rules/bam2vcf_fb.smk
- rules/bam2vcf_gatk.smk
- added bzip2 dependency for bedtools to work efficiently with compressed VCF (envs/bam2vcf.yml)
- sortVcf rule added before vcftools and bedtools rules for less memory usage (bam2vcf_fb and bam2vcf_gatk)
- rewrote intervals creation function to remedy list0 duplication (helperFun.py)
- added resource requests for multiple rules (resources.yaml)
- removed duplicated resource requests for bam2vcf workflows because freebayes resources were same name/request as gatk resources (resources.yaml)
- split and re-ordered GATK gatherVcfs rule into filterVcfs, gatherVcfs, and sortVcf (bam2vcf_fb and bam2vcf_gatk)
- changed SNPs per interval calculation from bedtools intersect to bedtools coverage for increased efficiency (bam2vcf_fb and bam2vcf_gatk)
> GATK rework

- .test/ecoli/config/config.yaml
- .test/ecoli/config/resources.yaml
- config/config.yaml
- config/resources.yaml
- workflow/Snakefile
- workflow/envs/callable.yml
- workflow/helperFun.py
- workflow/rules/bam2vcf.smk
- workflow/rules/callable_sites.smk
- workflow/rules/common.smk
- workflow/rules/fastq2bam.smk
- workflow/rules/intervals.smk
- workflow/scripts/create_coverage_bed.py
This pull request changes the way we do coverage calculations, to use mosdepth and d4tools instead of relying on bedtools unionbedgraph, which can be very slow for large sets.
> Use mosdepth d4tools to facilitate coverage calcs

- workflow/envs/callable.yml
- workflow/envs/fastq2bam.yml
- workflow/envs/sambamba.yml
This pull request makes sure that conda-forge is listed first in the channels, and pins versions of all tools.
> Fix conda envs

- workflow/Snakefile
This is a small PR to add a minimum version to snpArcher for easier debugging. Will prevent `Unexpected keyword default_target in rule definition (Snakefile, line 37)` errors.
> Add min_version

- workflow/rules/sentieon.smk
- workflow/rules/sumstats.smk
We originally set up the sentieon module to run with a trial license file. Production Sentieon licenses run by pinging a license on a server somewhere. This is the standard mode for running Sentieon, so I suggest we implement this as the default setting. Presumably, anyone with a license file could get this version to run by running the trial license, plus Sentieon support can help to troubleshoot this if it's a problem. 
The main change is switching the license from `input` to a `params`. You now specify the IP address that the license is running on, which sets the environmental variable that specifies the Sentieon license.
> Production ready Sentieon

- workflow/modules/qc/scripts/qc_dashboard_interactive.Rmd
the QC module originally only had north America for plotting. I set up some logical defaults to plot anything in the world and tweaked the settings around the scope of the map. I also reduced the number of PCs shown in figure 2, as it was quite crowded. Also, now the maps are produced even if there is no google API key provided.
> Qc map fix

- workflow/envs/cov_filter.yml
mosdepth 0.3.4 was compiled without --d4. Likely the best solution is to fix 0.3.3 until the conda package is updated.
> Fix mosdepth to 0.3.3 to resolve --d4 issue

- docs/executing.md
Was unable to test the environment using the example in the docs.
Was able to resolve the error by:
- Updating path from `./test/ecoli ` to `.test/ecoli` [`./.test/ecoli` would also work].
- Including `--use-conda` in the command, otherwise it was unable to build the environments
> Update path, enable conda

- .test/qc/config/config.yaml
- workflow/modules/qc/Snakefile
The QC rule subsample_snps currently removes mtDNA rather than the chromosomes specified by scaffolds_to_exclude. I've also updated the QC test to account for the scaffolds_to_exclude param.
> Add scaffolds_to_exclude param in QC

- workflow/modules/mk/Snakefile
Final output of degenotate is mk.tsv not mk_table.tsv
> Fix typo in mk module

- workflow/modules/postprocess/Snakefile
- workflow/modules/qc/Snakefile
- workflow/rules/cov_filter.smk
Adds resources to define memory for a few rules that are otherwise missing resources statements to hopefully avoid the current issue where the inferred defaults are massively to big and cause jobs to fail, e.g. #153, #148.
Might be a better way to do this in the future as we move to a different way to support slurm, but for now hopefully this will fix problems.
> Add resources to rules

- workflow/modules/qc/scripts/qc_dashboard_render.R
file.rename doesn't work if src and dest are on different filesystems. use file.copy instead. solves #166
> fix issue with qc-dashboard on different filesystems

- .test/ci/config/config.yaml
- .test/ecoli/config/config.yaml
- workflow/rules/bam2vcf_gatk.smk
- workflow/rules/bam2vcf_gatk_intervals.smk
- workflow/rules/common.smk
- workflow/rules/cov_filter.smk
- workflow/rules/sentieon.smk
- workflow/rules/sumstats.smk
adds optional dedup. default is to mark duplicates. if skipping marking duplicates, need to add `--notemp` when executing snakemake to preserve bams.
> Feat  optional dedup

- workflow/rules/common.smk
- workflow/rules/fastq.smk
Should help with #183. I suspect whatever error occured in fastp in that issue was written to the summary.out, which then got deleted by snakemake
> use json summary from fastp to make sure all stdout/stderr goes to log

- .test/ci/config/config.yaml
- .test/ecoli/config/config.yaml
- config/config.yaml
- docs/setup.md
- workflow/envs/fastq2bam.yml
- workflow/rules/fastq.smk
Every so often (way more often than seems reasonable) reads are delivered to me unsorted by read name. This happens pretty often with reads downloaded from NCBI as well. I added a config option to sort reads by name using bbmaps read sorter, which seems to be efficient in my experience. 
It's fast enough that I almost wonder if it should be the default to sort reads, but I guess for most use cases, it's best to have it be user-defined. 
It's a little inelegant how I set it up, just a bash ifelse statement, but it works...
> add config option to sort reads with bbmap before read trimming

- workflow/modules/qc/scripts/qc_dashboard_interactive.Rmd
I had a user write to me who pointed out that the number of SNPs reported in the HTML file don't match up with the VCF. This is because I originally interpreted the first line of the vcftools summary file to report all discovered SNPs (in raw vcf), when it is actually the number of SNPs that pass the filter flags. This PR updates the tabulation so the HTML correctly reports the total number of SNPs discovered, the number filtered, and the correct theta.
> Fix snp summary

- workflow/modules/postprocess/Snakefile
I'm addressing two issues here. The first is that our maf filter isn't correctly set in the strict filter (we don't remove SNPs at 1-params.maf) and I think this is a necessary change. The second is identifying SNP positions that are of length > 1 and removing them. 
Here is an example of a site that is retained by the filters currently:
```
JALCYL010000001.1       775994  .       AC      CC      11928.3 .
```
The original raw vcf call is as follows:
```
JALCYL010000001.1       775994  .       AC      CC,A    11928.28        .
```
So in postprocessing, we remove the deletion, but the length of the genotype doesn't change. We could probably recode these as SNPs, but given that SNPs overlapping indels are more likely to be errors, it seems sensible to just remove them altogether. The …
> Postprocessing update

- workflow/modules/postprocess/Snakefile
- workflow/rules/sentieon.smk
two changes:
1. long overdue parallelization for the filter_vcfs step of the sentieon model. just use gnu parallel with the -L flag, then combine resulting VCFs
2. the snps within indel filter in postprocessing wasn't exactly correct. Switching to using -T instead of -R otherwise they get interpreted as regions
> parallel sentieon intervals and fix indel snps

- workflow/modules/postprocess/Snakefile
- workflow/modules/qc/Snakefile
These resource requests per rule override the default we set in the profile/config.yaml. To me this seems to only cause confusing problems. They were removed elsewhere in the workflow, but not in the modules. Removing them unless @tsackton see's a reason to keep them around?
> remove resources from rules

- workflow/modules/trackhub/Snakefile
- workflow/modules/trackhub/envs/trackhub.yml
This was a doozy to track down, but I have been having issues with bed sorting for plant species with chloroplasts when building track hubs. Similar to issues [here](https://groups.google.com/a/soe.ucsc.edu/g/genome/c/utzMtbvIBVQ). 
e.g. here's the end of a sorted.chrom.sizes that cause issues because it is sorted differently depending on if you do case-sorting or not:
```
SCAF_100        30392
SCAF_101        20804
SCAF_102        18621
SCAF_103        12751
chloroplast     155214
```
The solution is to case sort before running bedtools complement. Then sort the non callable sites file using bedSort (for whatever reason relating to locale, sort doesn't work for this). This seems most robust to variation on different linux configurations of locale.
> fix issue with trackhub

- workflow/rules/common.smk
- workflow/rules/fastq.smk
This should fix #225. Snakemake doesn't know about the sorted reads intermediate files leading to weird things happening. 
This PR just breaks sort reads into its own rule and uses the config option to request the right files.
> make sort reads its own rule

- workflow/envs/cov_filter.yml
- workflow/rules/cov_filter.smk
clam currently produces a callable bed file that is perbase, which makes bedtools use lots of ram. while i work on a fix for this in clam, this should alleviate this issue
> fix: use bedtk to merge clam callable bed b/c its more mem efficient
